config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Defines the root path route ("/")
  # root "posts#index"
  root to: 'articles#index'
  resources :articles do
<<<<<<< HEAD
    resources :comments, only: [:new, :create, :destroy]
=======
    resources :comments, only: [:new, :create]

    resource :like, only: [:create, :destroy]

>>>>>>> 814fc0bc0384476bec993dac7d2b5a8d50c82a8b
  end
  resource :profile, only: [:show, :edit, :update]
  resources :favorites, only: [:index]
end

app/models/article.rb
# == Schema Information
#
# Table name: articles
#
#  id         :integer          not null, primary key
#  content    :text             not null
#  title      :string           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  user_id    :integer          not null
#
# Indexes
#
#  index_articles_on_user_id  (user_id)
#
class Article < ApplicationRecord
  validates :title, presence: true
  # length: { minimum: 5, maximum: 100 }
  validates :title, length: { minimum: 2, maximum: 100 }
  validates :title, format: { with: /\A(?!\@)/ }
  validates :content, presence: true
  validates :content, length: { minimum: 10 }
  validates :content, uniqueness: true

  validate :validate_title_and_content_length

  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  belongs_to :user

  def display_created_at
    I18n.l(self.created_at, format: :default)
  end

  def author_name
    user.display_name
  end

  def like_count
    likes.count
  end

  private
  def validate_title_and_content_length
    char_count = self.title.length + self.content.length
    unless char_count > 100
      errors.add(:content, '100文字以上でなければなりません')
    end
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [ :show ]
  before_action :authenticate_user!, only: [ :new, :create, :edit, :update, :destroy ]
  def index
    @articles = Article.all
  end

  def show
    @comments = @article.comments
  end

  def new
    @article = current_user.articles.build
  end

  def create
    @article = current_user.articles.build(article_params)
    if @article.save
      redirect_to article_path(@article), notice: '保存できたよ'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @article = current_user.articles.find(params[:id])
  end

  def update
    @article =current_user.articles.find(params[:id])
    if @article.update(article_params)
      redirect_to article_path(@article), notice: '更新できました'
    else
      flash.now[:error] = '更新できませんでした'
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    article = current_user.articles.find(params[:id])
    article.destroy!
    redirect_to root_path, status: :see_other, notice: '削除に成功しました'
  end

  private
  def article_params
    params.require(:article).permit(:title, :content)
  end

  def set_article
    @article = Article.find(params[:id])
  end
end

app/views/articles/_article.html.erb
<%= link_to article_path(id: article.id) do %>
    <div class="card">
    <div class="card_image">
      <%= image_tag 'eyecatch1.png' %>
    </div>
     <div class="card_title">
          <%= article.title %>
    </div>
      <div class="card_heart">
        <%= image_tag 'heart.svg' %>
        <span>23</span>
      </div>
      <div class="card_detail">
        <%= image_tag 'default-avatar.png' %>
        <div>
          <p>cohki0305</p>
          <p><%= article.display_created_at %></p>
        </div>
      </div>
    </div>
  </div>
  <% end %>

app/views/articles/_article.html.haml
= link_to article_path(id: article.id) do
  .card
    .card_image
      = image_tag 'eyecatch1.png'
    .card_title
      = article.title
    .card_heart
      = image_tag 'heart.svg'
      %span 23
    .card_detail
      = image_tag 'default-avatar.png'
      %div
        -# - if article.user.present?
        %p= article.author_name
        %p= article.display_created_at

app/views/articles/_form.html.erb
<div class="container">
<ul>
<% @article.errors.full_messages.each do |message| %>
  <li><%= message %></li>
<% end %>
</ul>
  <%= form_with(model: @article, url:articles_path, method: 'post',local: true) do |f| %>
  <div>
  <%= f.label  :title,'タイトル' %>
  </div>
  <div>
  <%= f.text_field  :title, class: 'text' %>
  </div>
  <div>
  <%= f.label  :content,'内容' %>
  </div>
  <div>
  <%= f.text_area  :content %>
  </div>
  <div>
  <%= f.submit '保存', class: 'btn-primary' %>
  </div>
  <% end %>
  </div>

app/views/articles/_form.html.haml
.container
  %ul
    - @article.errors.full_messages.each do |message|
      %li= message
  = form_with(model: @article, url:articles_path, method: 'post',local: true) do |f|
    %div
      = f.label  :title,'タイトル'
    %div
      = f.text_field  :title, class: 'text'
    %div
      = f.label  :content,'内容'
    %div
      = f.text_area  :content
    %div
      = f.submit '保存', class: 'btn-primary'

app/views/articles/_tabs.html.haml
.tabs
  .tabs_item.active
    新着記事一覧
  .tabs_item
    タイムライン

app/views/articles/about.html.erb
<h1>about</h1>

<%= link_to 'HOME', root_path %>

app/views/articles/about.html.haml
%h1 about
= link_to 'HOME', root_path

app/views/articles/edit.html.haml
= render 'form', article: @article

app/views/articles/index.html.erb
<div class="container">
<%= render 'tabs' %>

<% @articles.each do |article| %>
 <%= render 'article', article: article %>
<% end %>

<%= link_to new_article_path do %>
<div class="float_btn">
<i class="fa fa-plus"></i>
</div>
<% end %>
</div>

app/views/articles/index.html.haml
.container
  = render 'tabs'
  - @articles.each do |article|
    = render 'commons/article', article: article
  = link_to new_article_path do
    .float_btn
      %i.fa.fa-plus

app/views/articles/new.html.erb
<%= render 'form', article: @article %>

app/views/articles/new.html.haml
= render 'form', article: @article

app/views/articles/show.html.erb
<div class="article">
  <h1 class="article_title"><%= @article.title %></h1>
  <div class="article_detail">
    <%= image_tag 'default-avatar.png' %>
    <div>
      <p>cohki0305</p>
      <p><%= @article.display_created_at %></p>
    </div>
      <div class="article_detail_actions">
      <div class="dropdown">
        <%= image_tag 'actions.svg', class: 'dropbtn' %>
        <div class="dropdown-content mini">
        <%= link_to '編集する', edit_article_path(@article) %>
        <%= link_to '削除する', article_path(@article), data: { turbo_method: 'delete', turbo_confirm: '本当に削除してもよろしいですか？' } %>
        </div>
      </div>
    </div>
  </div>
  <div class="article_content">
    <%= @article.content %>
  </div>
  <div class="article_heart">
    <%= image_tag 'heart.svg' %>
  </div>
</div>

app/views/articles/show.html.haml
.article
 - if @article.eyecatch.attached?
  .article_image
    = image_tag @article.eyecatch
  %h1.article_title= @article.title
  .article_detail
    = image_tag @article.user.avatar_image
    %div
      %p= @article.author_name
      %p= @article.display_created_at
      - if user_signed_in? && current_user.has_written?(@article)
    .article_detail_actions
      .dropdown
        = image_tag 'actions.svg', class: 'dropbtn'
        .dropdown-content.mini
          = link_to '編集する', edit_article_path(@article)
          = link_to '削除する', article_path(@article), data: { turbo_method: 'delete', turbo_confirm: '本当に削除してもよろしいですか？' }
  .article_content
    = @article.content
    - if user_signed_in?
      - if current_user.has_liked?(@article)
  .article_heart
  = image_tag 'heart-active.svg'
  - else
  .article_heart
    = link_to article_like_path(@article), data: { method: 'post' } do
    = image_tag 'heart.svg'
  
  .article_comments
    %h2 コメント一覧
    - if @article.comments.any?
        - @article.comments.each do |comment|
          %p= comment.content

  .container
  = link_to new_article_comment_path(@article) do
    .btn-secondary
      コメントを追加