config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Defines the root path route ("/")
  # root "posts#index"
  root to: 'articles#index'
  resources :articles do
<<<<<<< HEAD
    resources :comments, only: [:new, :create, :destroy]
=======
    resources :comments, only: [:new, :create]

    resource :like, only: [:create, :destroy]

>>>>>>> 814fc0bc0384476bec993dac7d2b5a8d50c82a8b
  end
  resource :profile, only: [:show, :edit, :update]
  resources :favorites, only: [:index]
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "BlogApp" %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" crossorigin="anonymous">
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <header class="header">
      <div class="header_logos">
        <% if !current_page?(root_path) %>
          <%= link_to :back do %>
            <%= image_tag 'back.svg', class: 'header_back' %>
          <% end %>
        <% end %>
        <p class="header_pageTitle">BlogApp</p>
      </div>
      <div class="dropdown">
        <%= image_tag 'default-avatar.png', class: 'header_avatar dropbtn' %>
        <div class="dropdown-content">
          <a href="#">プロフィール</a>
          <a href="#">ログアウト</a>
        </div>
        </div>
        </header>
        <% if flash.present? %>
       <div class="flash">
        <% flash.each do |key, value| %>
          <div class="<%= key %>"><%= value %></div>
        <% end %>
      </div>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title= content_for(:title) || "BlogApp"
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag "application", "data-turbo-track": "reload"
    = javascript_importmap_tags
    %meta{:content => "width=device-width,initial-scale=1", :name => "viewport"}/
    %link{:crossorigin => "anonymous", :href => "https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css", :rel => "stylesheet"}/
    = javascript_importmap_tags
  %body
    %header.header
      .header_logos
        - if !current_page?(root_path)
          = link_to :back do
            = image_tag 'back.svg', class: 'header_back'
        %p.header_pageTitle 
          = link_to 'BlogApp', root_path
         - if user_signed_in?
        .dropdown
          = image_tag current_user.avatar_image, class: 'header_avatar dropbtn'
          .dropdown-content
            = link_to 'プロフィール', profile_path
            = link_to 'お気に入り', favorites_path
            = link_to 'ログアウト', destroy_user_session_path, data: { method: 'delete' }
      - else
        = link_to 'ログイン', new_user_session_path, class: 'header_loginBtn'
    - if flash.present?
      .flash
        - flash.each do |key, value|
          %div{:class => key}= value
    = yield